import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import ChatHistory from "../components/ChatHistory";
import Chats from "../components/Chats";
import ErrorDisplay from "../components/ErrorDisplay";
import { getAllChats } from "./api/chats";
import { AppContextProvider, useAppContext } from "../utils/AppContext";
import DialogGuide from "../components/DialogGuide";

export default function Home({ prefetchedChats }) {
  return (
    <>
      <Head>
        <title>Alpaca.cpp Web UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContextProvider prefetchedChats={prefetchedChats}>
        <Main />
      </AppContextProvider>
    </>
  );
}

const Main = () => {
  const { error } = useAppContext();

  return (
    <main className="relative h-full w-full transition-width flex flex-col overflow-hidden items-stretch flex-1">
      {error?.type === 'ERR_NO_MODEL' && <DialogGuide.DownloadModelAndBinary error={error} />}
      {error?.type === 'ERR_WS' && <DialogGuide.ErrorCannotConnectWS />}

      <div className="w-screen h-screen mx-auto overflow-hidden bg-white p-0">
        <div className="flex overflow-x-hidden items-bottom">
          <ChatHistory />
          <Chats />
        </div>
      </div>{" "}
    </main>
  );
};

export async function getServerSideProps(context) {
  return {
    props: {
      prefetchedChats: await getAllChats(),
    }
  }
}

